name: snippets
dependencies:
# essential dependencies
- numpy=1.18.5
- pandas=1.0.5
- python=3.7.6
- pip=20.1.1
- scikit-learn=0.22.2.post1
- pyyaml=5.3.1
- pytest=5.4.3
- pytest-cov=2.10.0
- black=19.10b0
- nb_black=1.0.7
- pylint=2.5.3
- jupyterlab=2.1.5
- jupyter_conda=3.3.1
- matplotlib=3.2.2
